import { Product } from './beverage-service';

export const initialProducts: Product[] = [
  // 1-20: Refrescos Cola y Limón/Naranja
  { name: 'Coca-Cola Original 33cl', brand: 'Coca-Cola', price: 1.5, stock: 120 },
  { name: 'Coca-Cola Zero 33cl', brand: 'Coca-Cola', price: 1.5, stock: 150 },
  { name: 'Coca-Cola Light 33cl', brand: 'Coca-Cola', price: 1.5, stock: 80 },
  { name: 'Coca-Cola Zero Zero 33cl', brand: 'Coca-Cola', price: 1.6, stock: 90 },
  { name: 'Fanta Naranja 33cl', brand: 'Fanta', price: 1.4, stock: 110 },
  { name: 'Fanta Limón 33cl', brand: 'Fanta', price: 1.4, stock: 95 },
  { name: 'Fanta Zero Naranja 33cl', brand: 'Fanta', price: 1.5, stock: 60 },
  { name: 'Fanta Zero Limón 33cl', brand: 'Fanta', price: 1.5, stock: 50 },
  { name: 'Sprite 33cl', brand: 'Sprite', price: 1.4, stock: 100 },
  { name: 'Sprite Zero 33cl', brand: 'Sprite', price: 1.5, stock: 70 },
  { name: 'Pepsi Cola 33cl', brand: 'Pepsi', price: 1.3, stock: 130 },
  { name: 'Pepsi Max 33cl', brand: 'Pepsi', price: 1.3, stock: 140 },
  { name: 'Pepsi Light 33cl', brand: 'Pepsi', price: 1.3, stock: 65 },
  { name: '7Up 33cl', brand: '7Up', price: 1.35, stock: 90 },
  { name: '7Up Free 33cl', brand: '7Up', price: 1.4, stock: 50 },
  { name: 'KAS Naranja 33cl', brand: 'KAS', price: 1.25, stock: 85 },
  { name: 'KAS Limón 33cl', brand: 'KAS', price: 1.25, stock: 80 },
  { name: 'Schweppes Tónica 25cl', brand: 'Schweppes', price: 1.6, stock: 200 },
  { name: 'Schweppes Limón 25cl', brand: 'Schweppes', price: 1.5, stock: 90 },
  { name: 'Royal Bliss Tonic 20cl', brand: 'Royal Bliss', price: 1.75, stock: 150 },

  // 21-40: Tónicas, Ginger Ale y refrescos premium
  { name: 'Royal Bliss Yuzu Tonic 20cl', brand: 'Royal Bliss', price: 1.8, stock: 120 },
  { name: 'Fever-Tree Premium Tonic 20cl', brand: 'Fever-Tree', price: 2.1, stock: 180 },
  { name: 'Fever-Tree Mediterranean 20cl', brand: 'Fever-Tree', price: 2.1, stock: 140 },
  { name: 'Fever-Tree Ginger Ale 20cl', brand: 'Fever-Tree', price: 2.2, stock: 100 },
  { name: 'Fever-Tree Ginger Beer 20cl', brand: 'Fever-Tree', price: 2.3, stock: 90 },
  { name: 'Appletiser 27.5cl', brand: 'Appletiser', price: 1.95, stock: 75 },
  { name: 'Nestea Limón 33cl', brand: 'Nestea', price: 1.6, stock: 160 },
  { name: 'Nestea Mango Piña 33cl', brand: 'Nestea', price: 1.7, stock: 80 },
  { name: 'Nestea Melocotón 33cl', brand: 'Nestea', price: 1.6, stock: 70 },
  { name: 'Aquarius Limón 33cl', brand: 'Aquarius', price: 1.55, stock: 210 },
  { name: 'Aquarius Naranja 33cl', brand: 'Aquarius', price: 1.55, stock: 190 },
  { name: 'Aquarius Zero Limón 33cl', brand: 'Aquarius', price: 1.65, stock: 100 },
  { name: 'Lipton Ice Tea Limón 33cl', brand: 'Lipton', price: 1.45, stock: 110 },
  { name: 'Lipton Ice Tea Melocotón 33cl', brand: 'Lipton', price: 1.45, stock: 90 },
  { name: 'TriNa Naranja 33cl', brand: 'TriNa', price: 1.35, stock: 85 },
  { name: 'TriNa Limón 33cl', brand: 'TriNa', price: 1.35, stock: 60 },
  { name: 'TriNa Manzana 33cl', brand: 'TriNa', price: 1.35, stock: 55 },
  { name: 'Bitter Kas 20cl', brand: 'KAS', price: 1.5, stock: 130 },
  { name: 'Cini Mini Bitter 20cl', brand: 'Cini', price: 1.4, stock: 40 },
  { name: 'San Pellegrino Aranciata 33cl', brand: 'San Pellegrino', price: 1.85, stock: 95 },

  // 41-60: Aguas Minerales (Con y Sin Gas)
  { name: 'Agua Lanjarón 50cl', brand: 'Lanjarón', price: 0.6, stock: 400 },
  { name: 'Agua Lanjarón 1.5L', brand: 'Lanjarón', price: 0.95, stock: 350 },
  { name: 'Agua Solán de Cabras 50cl', brand: 'Solán de Cabras', price: 0.9, stock: 300 },
  { name: 'Agua Solán de Cabras 1.5L', brand: 'Solán de Cabras', price: 1.4, stock: 250 },
  { name: 'Agua Solán de Cabras Gas 75cl', brand: 'Solán de Cabras', price: 1.65, stock: 120 },
  { name: 'Agua Bezoya 50cl', brand: 'Bezoya', price: 0.55, stock: 450 },
  { name: 'Agua Bezoya 1.5L', brand: 'Bezoya', price: 0.85, stock: 400 },
  { name: 'Agua Font Vella 50cl', brand: 'Font Vella', price: 0.58, stock: 380 },
  { name: 'Agua Font Vella 1.5L', brand: 'Font Vella', price: 0.9, stock: 320 },
  { name: 'Agua Evian 50cl', brand: 'Evian', price: 1.35, stock: 150 },
  { name: 'Agua Evian 1.5L', brand: 'Evian', price: 2.1, stock: 100 },
  { name: 'Agua Vichy Catalan 25cl', brand: 'Vichy Catalan', price: 0.95, stock: 220 },
  { name: 'Agua Vichy Catalan 50cl', brand: 'Vichy Catalan', price: 1.4, stock: 180 },
  { name: 'Agua Vichy Catalan 1L', brand: 'Vichy Catalan', price: 1.95, stock: 150 },
  { name: 'Agua Vichy Catalan Limón 33cl', brand: 'Vichy Catalan', price: 1.25, stock: 110 },
  { name: 'Agua Perrier 33cl', brand: 'Perrier', price: 1.45, stock: 160 },
  { name: 'Agua Perrier 75cl', brand: 'Perrier', price: 2.25, stock: 90 },
  { name: 'Agua San Pellegrino 25cl', brand: 'San Pellegrino', price: 1.2, stock: 130 },
  { name: 'Agua San Pellegrino 75cl', brand: 'San Pellegrino', price: 2.1, stock: 110 },
  { name: 'Agua Cabreiroá 50cl', brand: 'Cabreiroá', price: 0.65, stock: 200 },

  // 61-80: Cervezas Nacionales
  { name: 'Estrella Galicia Especial 33cl', brand: 'Estrella Galicia', price: 1.4, stock: 300 },
  { name: 'Estrella Galicia 1906 Reserva 33cl', brand: 'Estrella Galicia', price: 1.8, stock: 200 },
  { name: 'Estrella Galicia 1906 Red Vintage 33cl', brand: 'Estrella Galicia', price: 1.9, stock: 150 },
  { name: 'Estrella Galicia 0,0% 33cl', brand: 'Estrella Galicia', price: 1.3, stock: 180 },
  { name: 'Mahou Cinco Estrellas 33cl', brand: 'Mahou', price: 1.25, stock: 400 },
  { name: 'Mahou Clásica 33cl', brand: 'Mahou', price: 1.15, stock: 250 },
  { name: 'Mahou Maestra Doble Lúpulo 33cl', brand: 'Mahou', price: 1.6, stock: 140 },
  { name: 'Mahou 0,0 Tostada 33cl', brand: 'Mahou', price: 1.3, stock: 160 },
  { name: 'San Miguel Especial 33cl', brand: 'San Miguel', price: 1.2, stock: 300 },
  { name: 'San Miguel Selecta 33cl', brand: 'San Miguel', price: 1.5, stock: 120 },
  { name: 'Cruzcampo Especial 33cl', brand: 'Cruzcampo', price: 1.18, stock: 350 },
  { name: 'Cruzcampo Gran Reserva 33cl', brand: 'Cruzcampo', price: 1.6, stock: 130 },
  { name: 'Alhambra Reserva 1925 33cl', brand: 'Alhambra', price: 1.75, stock: 280 },
  { name: 'Alhambra Reserva Roja 33cl', brand: 'Alhambra', price: 1.9, stock: 140 },
  { name: 'Alhambra Especial 33cl', brand: 'Alhambra', price: 1.3, stock: 180 },
  { name: 'Estrella Damm 33cl', brand: 'Damm', price: 1.25, stock: 320 },
  { name: 'Voll-Damm Doble Malta 33cl', brand: 'Damm', price: 1.65, stock: 240 },
  { name: 'Free Damm 0,0 33cl', brand: 'Damm', price: 1.25, stock: 150 },
  { name: 'Turia Marzen 33cl', brand: 'Turia', price: 1.45, stock: 170 },
  { name: 'Ambar Especial 33cl', brand: 'Ambar', price: 1.22, stock: 130 },

  // 81-100: Cervezas de Importación y Artesanales
  { name: 'Heineken 33cl', brand: 'Heineken', price: 1.45, stock: 280 },
  { name: 'Heineken 0,0% 33cl', brand: 'Heineken', price: 1.5, stock: 150 },
  { name: 'Corona Extra 35.5cl', brand: 'Corona', price: 1.85, stock: 220 },
  { name: 'Budweiser 33cl', brand: 'Budweiser', price: 1.4, stock: 190 },
  { name: 'Stella Artois 33cl', brand: 'Stella Artois', price: 1.6, stock: 140 },
  { name: 'Paulaner Hefe-Weissbier 50cl', brand: 'Paulaner', price: 2.3, stock: 160 },
  { name: 'Paulaner Salvator 33cl', brand: 'Paulaner', price: 2.1, stock: 80 },
  { name: 'Franziskaner Weissbier 50cl', brand: 'Franziskaner', price: 2.25, stock: 150 },
  { name: 'Guinness Draft 44cl', brand: 'Guinness', price: 2.45, stock: 180 },
  { name: 'Leffe Blonde 33cl', brand: 'Leffe', price: 1.95, stock: 130 },
  { name: 'Leffe Brown 33cl', brand: 'Leffe', price: 2.05, stock: 90 },
  { name: 'Duvel Golden Ale 33cl', brand: 'Duvel', price: 2.95, stock: 110 },
  { name: 'Chimay Azul Trappist 33cl', brand: 'Chimay', price: 3.25, stock: 85 },
  { name: 'Desperados Tequila Beer 33cl', brand: 'Desperados', price: 1.85, stock: 160 },
  { name: 'BrewDog Punk IPA 33cl', brand: 'BrewDog', price: 2.4, stock: 140 },
  { name: 'BrewDog Elvis Juice 33cl', brand: 'BrewDog', price: 2.6, stock: 95 },
  { name: 'Founders All Day IPA 33cl', brand: 'Founders', price: 2.5, stock: 80 },
  { name: 'La Chouffe Blonde 33cl', brand: 'La Chouffe', price: 2.8, stock: 105 },
  { name: 'Erdinger Weissbier 50cl', brand: 'Erdinger', price: 2.2, stock: 120 },
  { name: 'Birra Moretti 33cl', brand: 'Moretti', price: 1.5, stock: 140 },

  // 101-125: Bebidas Energéticas e Isotónicas
  { name: 'Red Bull Energy Drink 25cl', brand: 'Red Bull', price: 1.8, stock: 250 },
  { name: 'Red Bull Sugarfree 25cl', brand: 'Red Bull', price: 1.8, stock: 150 },
  { name: 'Red Bull Zero 25cl', brand: 'Red Bull', price: 1.8, stock: 90 },
  { name: 'Red Bull Red Edition (Sandía) 25cl', brand: 'Red Bull', price: 1.9, stock: 110 },
  { name: 'Red Bull Blue Edition (Arándanos) 25cl', brand: 'Red Bull', price: 1.9, stock: 85 },
  { name: 'Red Bull Green Edition (Cactus) 25cl', brand: 'Red Bull', price: 1.9, stock: 70 },
  { name: 'Monster Energy 50cl', brand: 'Monster', price: 2.1, stock: 220 },
  { name: 'Monster Ultra White 50cl', brand: 'Monster', price: 2.1, stock: 260 },
  { name: 'Monster Mango Loco 50cl', brand: 'Monster', price: 2.1, stock: 180 },
  { name: 'Monster Pipeline Punch 50cl', brand: 'Monster', price: 2.1, stock: 140 },
  { name: 'Monster Rossi 50cl', brand: 'Monster', price: 2.1, stock: 100 },
  { name: 'Monster Pacific Punch 50cl', brand: 'Monster', price: 2.1, stock: 95 },
  { name: 'Burn Original 25cl', brand: 'Burn', price: 1.45, stock: 130 },
  { name: 'Rockstar Original 50cl', brand: 'Rockstar', price: 1.95, stock: 120 },
  { name: 'Gatorade Naranja 50cl', brand: 'Gatorade', price: 1.75, stock: 160 },
  { name: 'Gatorade Azul (Cool Blue) 50cl', brand: 'Gatorade', price: 1.75, stock: 180 },
  { name: 'Gatorade Limón 50cl', brand: 'Gatorade', price: 1.75, stock: 120 },
  { name: 'Powerade Blue Storm 50cl', brand: 'Powerade', price: 1.8, stock: 230 },
  { name: 'Powerade Blood Orange 50cl', brand: 'Powerade', price: 1.8, stock: 110 },
  { name: 'Enervit Isotonic Drink 500g', brand: 'Enervit', price: 8.95, stock: 45 },
  { name: 'Nocco BCAA Limón-Del Sol 33cl', brand: 'Nocco', price: 2.5, stock: 75 },
  { name: 'Nocco BCAA Caribbean 33cl', brand: 'Nocco', price: 2.5, stock: 90 },
  { name: 'Prime Hydration Blue Raspberry 50cl', brand: 'Prime', price: 2.99, stock: 130 },
  { name: 'Prime Hydration Lemon Lime 50cl', brand: 'Prime', price: 2.99, stock: 110 },
  { name: 'Prime Hydration Tropical Punch 50cl', brand: 'Prime', price: 2.99, stock: 140 },

  // 126-150: Vinos Tintos, Blancos y Rosados
  { name: 'Vino Tinto Ramón Bilbao Crianza 75cl', brand: 'Ramón Bilbao', price: 9.5, stock: 80 },
  { name: 'Vino Tinto Protos Roble 75cl', brand: 'Protos', price: 8.9, stock: 95 },
  { name: 'Vino Tinto Protos Crianza 75cl', brand: 'Protos', price: 16.5, stock: 60 },
  { name: 'Vino Tinto Muga Crianza 75cl', brand: 'Muga', price: 18.2, stock: 55 },
  { name: 'Vino Tinto Marqués de Cáceres Crianza 75cl', brand: 'Marqués de Cáceres', price: 8.2, stock: 120 },
  { name: 'Vino Tinto Sangre de Toro 75cl', brand: 'Torres', price: 5.95, stock: 150 },
  { name: 'Vino Tinto Faustino VII 75cl', brand: 'Faustino', price: 5.1, stock: 140 },
  { name: 'Vino Tinto Emilio Moro 75cl', brand: 'Emilio Moro', price: 22.0, stock: 45 },
  { name: 'Vino Tinto Pago de Carraovejas 75cl', brand: 'Carraovejas', price: 39.5, stock: 25 },
  { name: 'Vino Blanco Viña Sol 75cl', brand: 'Torres', price: 6.2, stock: 110 },
  { name: 'Vino Blanco Verdejo José Pariente 75cl', brand: 'José Pariente', price: 10.5, stock: 85 },
  { name: 'Vino Blanco Verdejo Protos 75cl', brand: 'Protos', price: 7.2, stock: 90 },
  { name: 'Vino Blanco Albariño Martín Códax 75cl', brand: 'Martín Códax', price: 12.4, stock: 70 },
  { name: 'Vino Blanco Albariño Terras Gauda 75cl', brand: 'Terras Gauda', price: 15.9, stock: 65 },
  { name: 'Vino Blanco Mar de Frades 75cl', brand: 'Mar de Frades', price: 17.5, stock: 40 },
  { name: 'Vino Blanco Barbadillo Castillo de San Diego 75cl', brand: 'Barbadillo', price: 4.5, stock: 200 },
  { name: 'Vino Rosado Mateus Rose 75cl', brand: 'Mateus', price: 4.95, stock: 130 },
  { name: 'Vino Rosado Lambrusco Dell Emilia 75cl', brand: 'Riunite', price: 3.9, stock: 250 },
  { name: 'Vino Rosado Cresta Rosa 75cl', brand: 'Cresta Rosa', price: 4.8, stock: 90 },
  { name: 'Cava Freixenet Carta Nevada Semi Seco 75cl', brand: 'Freixenet', price: 6.95, stock: 110 },
  { name: 'Cava Codorníu Reina María Cristina 75cl', brand: 'Codorníu', price: 14.5, stock: 50 },
  { name: 'Champagne Moët & Chandon Brut Imperial 75cl', brand: 'Moët & Chandon', price: 42.5, stock: 35 },
  { name: 'Champagne Veuve Clicquot Yellow Label 75cl', brand: 'Veuve Clicquot', price: 48.0, stock: 30 },
  { name: 'Champagne Dom Pérignon Vintage 75cl', brand: 'Dom Pérignon', price: 210.0, stock: 10 },
  { name: 'Sidra El Gaitero Extra 70cl', brand: 'El Gaitero', price: 3.5, stock: 100 },

  // 151-175: Licores y Bebidas Espirituosas (Whisky, Ginebra, Ron, Vodka)
  { name: 'Whisky Johnnie Walker Red Label 70cl', brand: 'Johnnie Walker', price: 14.5, stock: 110 },
  { name: 'Whisky Johnnie Walker Black Label 70cl', brand: 'Johnnie Walker', price: 26.9, stock: 75 },
  { name: 'Whisky J&B Rare 70cl', brand: 'J&B', price: 12.95, stock: 120 },
  { name: 'Whisky Ballantines Finest 70cl', brand: 'Ballantines', price: 13.4, stock: 95 },
  { name: 'Whisky Jameson Irish 70cl', brand: 'Jameson', price: 17.5, stock: 80 },
  { name: 'Whisky Jack Daniels Old No. 7 70cl', brand: 'Jack Daniels', price: 22.5, stock: 100 },
  { name: 'Whisky Cardhu 12 Años Single Malt 70cl', brand: 'Cardhu', price: 28.5, stock: 45 },
  { name: 'Whisky Macallan 12 Años Double Cask 70cl', brand: 'Macallan', price: 72.0, stock: 20 },
  { name: 'Ginebra Beefeater London Dry 70cl', brand: 'Beefeater', price: 14.2, stock: 115 },
  { name: 'Ginebra Tanqueray London Dry 70cl', brand: 'Tanqueray', price: 16.9, stock: 90 },
  { name: 'Ginebra Tanqueray Ten 70cl', brand: 'Tanqueray', price: 29.5, stock: 40 },
  { name: 'Ginebra Seagrams Extra Dry 70cl', brand: 'Seagrams', price: 15.5, stock: 105 },
  { name: 'Ginebra Hendricks 70cl', brand: 'Hendricks', price: 29.9, stock: 60 },
  { name: 'Ginebra Puerto de Indias Strawberry 70cl', brand: 'Puerto de Indias', price: 15.9, stock: 130 },
  { name: 'Ginebra Nordés Atlantic Galician 70cl', brand: 'Nordés', price: 24.5, stock: 70 },
  { name: 'Ginebra Bombay Sapphire 70cl', brand: 'Bombay', price: 19.9, stock: 80 },
  { name: 'Ron Barceló Añejo 70cl', brand: 'Barceló', price: 14.9, stock: 160 },
  { name: 'Ron Brugal Añejo 70cl', brand: 'Brugal', price: 14.7, stock: 140 },
  { name: 'Ron Cacique Añejo 70cl', brand: 'Cacique', price: 13.9, stock: 120 },
  { name: 'Ron Havana Club 7 Años 70cl', brand: 'Havana Club', price: 21.5, stock: 85 },
  { name: 'Ron Santa Teresa 1796 Solera 70cl', brand: 'Santa Teresa', price: 39.9, stock: 30 },
  { name: 'Ron Bacardi Carta Blanca 70cl', brand: 'Bacardi', price: 12.5, stock: 150 },
  { name: 'Vodka Absolut 70cl', brand: 'Absolut', price: 13.9, stock: 125 },
  { name: 'Vodka Smirnoff Red 70cl', brand: 'Smirnoff', price: 11.5, stock: 110 },
  { name: 'Vodka Grey Goose 70cl', brand: 'Grey Goose', price: 38.5, stock: 35 },

  // 176-200: Licores Variados, Vermuts, Anises y Zumos
  { name: 'Vodka Belvedere 70cl', brand: 'Belvedere', price: 39.9, stock: 30 },
  { name: 'Tequila Jose Cuervo Especial Reposado 70cl', brand: 'Jose Cuervo', price: 16.5, stock: 70 },
  { name: 'Tequila Don Julio Reposado 70cl', brand: 'Don Julio', price: 49.5, stock: 25 },
  { name: 'Licor Baileys Irish Cream 70cl', brand: 'Baileys', price: 13.9, stock: 120 },
  { name: 'Licor Jägermeister 70cl', brand: 'Jägermeister', price: 14.95, stock: 145 },
  { name: 'Licor Cointreau 70cl', brand: 'Cointreau', price: 19.9, stock: 50 },
  { name: 'Licor Disaronno Amaretto 70cl', brand: 'Disaronno', price: 15.9, stock: 65 },
  { name: 'Licor Licor 43 70cl', brand: 'Diego Zamora', price: 14.5, stock: 90 },
  { name: 'Anís del Mono Dulce 70cl', brand: 'Anís del Mono', price: 9.5, stock: 80 },
  { name: 'Ginebra Larios 12 70cl', brand: 'Larios', price: 13.5, stock: 75 },
  { name: 'Vermut Martini Bianco 1L', brand: 'Martini', price: 8.95, stock: 110 },
  { name: 'Vermut Martini Rosso 1L', brand: 'Martini', price: 8.95, stock: 95 },
  { name: 'Vermut Yzaguirre Rojo Reserva 1L', brand: 'Yzaguirre', price: 10.9, stock: 60 },
  { name: 'Aperitivo Aperol 70cl', brand: 'Aperol', price: 12.4, stock: 130 },
  { name: 'Aperitivo Campari 70cl', brand: 'Campari', price: 14.9, stock: 90 },
  { name: 'Zumo Granini Naranja 1L', brand: 'Granini', price: 1.95, stock: 160 },
  { name: 'Zumo Granini Piña 1L', brand: 'Granini', price: 1.95, stock: 140 },
  { name: 'Zumo Granini Melocotón 1L', brand: 'Granini', price: 1.95, stock: 120 },
  { name: 'Zumo Granini Manzana 1L', brand: 'Granini', price: 1.95, stock: 90 },
  { name: 'Zumo Granini Tomate 1L', brand: 'Granini', price: 2.1, stock: 50 },
  { name: 'Zumo Juver Disfruta 10 Frutas 1L', brand: 'Juver', price: 1.4, stock: 150 },
  { name: 'Tónica Nordic Mist 25cl', brand: 'Nordic Mist', price: 1.2, stock: 120 },
  { name: 'Sangría Don Simón 1.5L', brand: 'Don Simón', price: 2.5, stock: 200 },
  { name: 'Tinto de Verano Don Simón Limón 1.5L', brand: 'Don Simón', price: 2.3, stock: 180 },
  { name: 'Tinto de Verano Don Simón Clásico 1.5L', brand: 'Don Simón', price: 2.3, stock: 150 }
];
